Repository Shopify/tapioca, pull requests merged in 2021-11, with the labels that each got.

#581 Bump `sorbet` and `sorbet-runtime`
  Gemfile.lock
Labels: dependencies

#583 Move `Fork` and `Subprocess` back to `Isolation`
  lib/tapioca/helpers/test/isolation.rb
  lib/tapioca/ruby_ext/forking_patch.rb
  lib/tapioca/ruby_ext/subprocess_patch.rb
Labels: ignore-for-release

#555 Support ActiveRecord::Enum for abstract classes
  lib/tapioca/compilers/dsl/active_record_enum.rb
  spec/tapioca/compilers/dsl/active_record_enum_spec.rb
Labels: bugfix

#590 Fix doc generation on CI
  lib/tapioca/compilers/dsl/identity_cache.rb
  spec/tapioca/compilers/dsl/identity_cache_spec.rb
Labels: chore

#589 Fix eval'ed constants not being generated in gem RBI generation
  lib/tapioca/constant_locator.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: bugfix

#588 Update `README.md` usage docs
  README.md
Labels: chore

#584 Add `MissingConstantError` messaging
  lib/tapioca/compilers/dsl/active_record_associations.rb
  spec/tapioca/compilers/dsl/active_record_associations_spec.rb
Labels: enhancement

#587 Generate typed store accessors in their own module
  lib/tapioca/compilers/dsl/active_record_typed_store.rb
  manual/generator_activerecordtypedstore.md
  spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
Labels: enhancement

#593 Replace `remove` method and use `remove_file`
  lib/tapioca/generators/base.rb
  lib/tapioca/generators/dsl.rb
  lib/tapioca/generators/gem.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/cli/gem_spec.rb
Labels: chore

#594 Add command help docs to `README.md`
  README.md
Labels: chore

#596 Ignore Dependabot updates in release notes
  .github/dependabot.yml
Labels: chore

#599 Re-add default labels for Dependabot PRs
  .github/dependabot.yml
Labels: chore, ignore-for-release

#622 Add spin bootstrap script
  .spin/bootstrap
Labels: chore

#625 Extract CliHelper
  lib/tapioca/cli.rb
  lib/tapioca/generators/base.rb
  lib/tapioca/helpers/cli_helper.rb
  lib/tapioca/internal.rb
Labels: enhancement

#631 Generate RBIs with documentation by default
  sorbet/tapioca/config.yml
Labels: chore

#630 Bump `rbi` to v0.0.8
  Gemfile.lock
  sorbet/rbi/gems/rbi@0.0.8.rbi
  spec/tapioca/compilers/dsl/aasm_spec.rb
  spec/tapioca/compilers/dsl/active_record_enum_spec.rb
Labels: dependencies

#638 Bump `sorbet` and `sorbet-runtime`
  Gemfile.lock
Labels: dependencies

#639 Eager load constants registered for `autoload` after loading gems
  lib/tapioca.rb
  lib/tapioca/autoload_tracker.rb
  lib/tapioca/compilers/symbol_table/symbol_generator.rb
  lib/tapioca/generators/gem.rb
  lib/tapioca/reflection.rb
  spec/tapioca/cli/gem_spec.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: enhancement
