Repository Shopify/tapioca, pull requests merged in 2021-12, with the labels that each got.

#642 Stop intercepting `Module#autoload` with a prepend
  lib/tapioca/autoload_tracker.rb
  spec/tapioca/cli/gem_spec.rb
Labels: enhancement

#643 Bump `sorbet` and `sorbet-runtime`
  Gemfile.lock
Labels: dependencies

#641 Add a command to clean shim files automatically
  Gemfile.lock
  lib/tapioca/cli.rb
  lib/tapioca/config.rb
  spec/tapioca/cli/clean_shims_spec.rb
  tapioca.gemspec
Labels: feature

#651 Improve autoload `Kernel` hooks so that they actually work now
  lib/tapioca/autoload_tracker.rb
  spec/tapioca/cli/gem_spec.rb
Labels: bugfix

#650 Bump `google-protobuf` gem for `dev` compatibility
  Gemfile.lock
  sorbet/rbi/gems/google-protobuf@3.17.3.rbi
  sorbet/rbi/gems/google-protobuf@3.19.1.rbi
  spec/tapioca/compilers/dsl/protobuf_spec.rb
Labels: chore

#654 Rename and group tracker classes
  lib/tapioca.rb
  lib/tapioca/autoload_tracker.rb
  lib/tapioca/compilers/symbol_table/symbol_generator.rb
  lib/tapioca/constant_locator.rb
  lib/tapioca/generators/gem.rb
  lib/tapioca/helpers/mixin_type.rb
  lib/tapioca/mixin_tracker.rb
  lib/tapioca/trackers.rb
  lib/tapioca/trackers/autoload.rb
  lib/tapioca/trackers/constant_definition.rb
  lib/tapioca/trackers/mixin.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: chore

#660 Allow DSL generators to change behaviour based on if `ActiveRecordRelations` is enabled or not
  lib/tapioca/compilers/dsl/active_record_associations.rb
  lib/tapioca/compilers/dsl/active_record_scope.rb
  lib/tapioca/compilers/dsl/base.rb
  lib/tapioca/compilers/dsl_compiler.rb
  lib/tapioca/generators/dsl.rb
  spec/dsl_spec_helper.rb
  spec/tapioca/compilers/dsl/active_record_associations_spec.rb
  spec/tapioca/compilers/dsl/active_record_scope_spec.rb
Labels: enhancement

#659 Refactor config infrastructure to be integrated with Thor
  README.md
  lib/tapioca.rb
  lib/tapioca/cli.rb
  lib/tapioca/compilers/dsl/base.rb
  lib/tapioca/config.rb
  lib/tapioca/config_builder.rb
  lib/tapioca/generators/dsl.rb
  lib/tapioca/generators/gem.rb
  lib/tapioca/generators/todo.rb
  lib/tapioca/helpers/config_helper.rb
  lib/tapioca/internal.rb
  sorbet/tapioca/config.yml
  spec/tapioca/cli/clean_shims_spec.rb
  spec/tapioca/cli/deprecations_spec.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: breaking-change

#662 Make `init` create a skeleton Tapioca config
  lib/tapioca/cli.rb
  lib/tapioca/generators/init.rb
  spec/tapioca/cli/init_spec.rb
Labels: enhancement

#663 Simplify and encapsulate binstub creation logic
  lib/tapioca/generators/init.rb
Labels: chore

#675 Add typing for find_by!
  lib/tapioca/compilers/dsl/active_record_relations.rb
  spec/tapioca/compilers/dsl/active_record_relations_spec.rb
Labels: bug, bugfix

#678 Refactor how `SmartProperties` methods are generated
  lib/tapioca/compilers/dsl/smart_properties.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/compilers/dsl/smart_properties_spec.rb
Labels: bugfix
