Repository Shopify/tapioca, pull requests merged in 2022-03, with the labels that each got.

#839 Fix generic type variable argument serialization
  lib/tapioca/runtime/generic_type_registry.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: bugfix

#818 Need less entries in `require.rb`
  lib/tapioca/commands/gem.rb
  lib/tapioca/gemfile.rb
  sorbet/rbi/gems/activemodel-serializers-xml@1.0.2.rbi
  sorbet/rbi/gems/activemodel@6.1.4.6.rbi
  sorbet/rbi/gems/activerecord@6.1.4.6.rbi
  sorbet/rbi/gems/activesupport@6.1.4.6.rbi
  sorbet/rbi/gems/bcrypt@3.1.16.rbi
  sorbet/rbi/gems/rubocop-ast@1.15.2.rbi
  sorbet/rbi/gems/rubocop-lsp@0.1.6.rbi
  sorbet/rbi/gems/rubocop-rspec@2.8.0.rbi
  sorbet/rbi/gems/rubocop@1.25.1.rbi
  sorbet/rbi/gems/state_machines@0.5.0.rbi
  sorbet/rbi/gems/xpath@3.2.0.rbi
  sorbet/tapioca/require.rb
  spec/helpers/mock_project.rb
  spec/tapioca/cli/gem_spec.rb
Labels: enhancement

#841 Add an easy way to print `ExecResult` in tests
  spec/helpers/mock_project.rb
Labels: chore

#844 Add `tapioca/dsl` entrypoint for custom DSL compilers
  lib/tapioca/dsl.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: enhancement

#848 Always ignore the `vendor/` directory form the sorbet/config
  lib/tapioca/commands/init.rb
  spec/tapioca/cli/init_spec.rb
Labels: enhancement

#847 Do not crash when trying to generate DSL RBIs on non-rails apps
  lib/tapioca/dsl/compilers/active_record_fixtures.rb
  lib/tapioca/dsl/compilers/url_helpers.rb
  spec/tapioca/dsl/compilers/active_record_fixtures_spec.rb
Labels: bugfix

#873 Run Sorbet using Spoom's helper
  Gemfile.lock
  lib/tapioca/helpers/sorbet_helper.rb
  sorbet/rbi/gems/spoom@1.1.9.rbi
Labels: chore

#877 Start using compared by identity Set operations for `UrlHelpers#includes_helper?`
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/compilers/url_helpers.rb
  sorbet/rbi/shims/set.rbi
  spec/tapioca/dsl/compilers/url_helpers_spec.rb
Labels: bugfix

#878 Avoid generating syntax errors for capitalized protobuf fields
  lib/tapioca/dsl/compilers/protobuf.rb
  spec/tapioca/dsl/compilers/protobuf_spec.rb
Labels: bugfix
