Repository Shopify/tapioca, pull requests merged in 2022-05, with the labels that each got.

#918 Fix typo in `--quiet` option description
  README.md
  lib/tapioca/cli.rb
Labels: chore

#919 Add help command input in README snippets
  README.md
  tasks/readme.rake
Labels: chore

#920 Enable documentation generation by default
  README.md
  lib/tapioca/cli.rb
  sorbet/tapioca/config.yml
Labels: enhancement

#917 Improve README
  README.md
  misc/tapioca-logo.svg
Labels: documentation

#924 Explicitly load descendants patch in ActiveSupport
  lib/tapioca/runtime/loader.rb
Labels: bugfix

#930 Prototype: Add `annotations` command
  README.md
  lib/tapioca.rb
  lib/tapioca/cli.rb
  lib/tapioca/commands.rb
  lib/tapioca/commands/annotations.rb
  lib/tapioca/internal.rb
  lib/tapioca/repo_index.rb
  spec/tapioca/cli/annotations_spec.rb
Labels: feature

#933 Handle gracefully if we get unparsable JSON
  lib/tapioca/static/symbol_table_parser.rb
Labels: chore

#944 Fix type variable patch to respect references to late defined types
  lib/tapioca/sorbet_ext/generic_name_patch.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: bugfix

#932 Always run tests with `--no-doc` unless specified otherwise
  spec/helpers/mock_project.rb
Labels: chore

#954 Improve README documentation about `tapioca gem --all`
  README.md
Labels: documentation

#953 Fix typo in README
  README.md
Labels: documentation

#947 Skip debug and fakefs gems
  README.md
  lib/tapioca/gemfile.rb
Labels: bugfix
