Repository Shopify/tapioca, pull requests merged in 2022-07, with the labels that each got.

#1028 Fix Rails engine symbol loading
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/static/symbol_loader.rb
  spec/tapioca/cli/gem_spec.rb
Labels: bugfix

#1040 Do not mark constants as seen before generating RBI for them
  lib/tapioca/gem/pipeline.rb
  spec/tapioca/cli/gem_spec.rb
Labels: bug, bugfix

#1045 Fix method name validation edge-case
  lib/tapioca/helpers/rbi_helper.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
  spec/tapioca/helpers/rbi_helper_spec.rb
Labels: bugfix

#1054 Do not index files typed: ignore when running `check-shims`
  lib/tapioca/helpers/rbi_files_helper.rb
  spec/tapioca/cli/check_shims_spec.rb
Labels: bug, bugfix

#1055 Run command `check-shims` on CI
  .github/workflows/ci.yml
  sorbet/rbi/shims/rdoc.rbi
Labels: chore

#1057 Add CODEOWNERS to repo
  .github/CODEOWNERS
Labels: chore

#1056 Parallelize RBI parsing to speed up the `check-shims` command
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/commands/check_shims.rb
  lib/tapioca/helpers/rbi_files_helper.rb
  lib/tapioca/internal.rb
  spec/tapioca/cli/check_shims_spec.rb
Labels: enhancement

#1072 Extract gem and dsl loaders in a new API
  lib/tapioca/cli.rb
  lib/tapioca/commands/dsl.rb
  lib/tapioca/commands/gem.rb
  lib/tapioca/internal.rb
  lib/tapioca/loaders/dsl.rb
  lib/tapioca/loaders/gem.rb
  lib/tapioca/loaders/loader.rb
Labels: chore

#1077 Also check duplicated mixins in shims and TODO files
  lib/tapioca/helpers/rbi_files_helper.rb
  spec/tapioca/cli/check_shims_spec.rb
Labels: bugfix

#1074 Don't crash on rails < 7
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
Labels: bugfix
