Repository Shopify/tapioca, pull requests merged in 2022-02, with the labels that each got.

#769 Clean symbol loader
  lib/tapioca/compilers/symbol_table/symbol_loader.rb
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/internal.rb
  lib/tapioca/symbol_loader.rb
  lib/tapioca/symbol_table_parser.rb
Labels: chore

#783 Remove useless method `mixed_in_by_gem?` from SymbolTableCompiler
  lib/tapioca/compilers/symbol_table_compiler.rb
Labels: chore

#784 Rename symbol_ignored? -> symbol_in_payload?
  lib/tapioca/compilers/symbol_table_compiler.rb
Labels: chore

#782 SymbolTableCompiler returns a new tree each time called
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/generators/gem.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: chore

#789 Improve workspace settings for VSCode
  .vscode/settings.json
Labels: chore

#788 Expose DSL compiler test helper as a reusable unit
  lib/tapioca/helpers/test/dsl_compiler.rb
  lib/tapioca/helpers/test/template.rb
  spec/dsl_spec_helper.rb
  spec/tapioca/compilers/dsl/aasm_spec.rb
  spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
  spec/tapioca/compilers/dsl/action_mailer_spec.rb
  spec/tapioca/compilers/dsl/active_job_spec.rb
  spec/tapioca/compilers/dsl/active_model_attributes_spec.rb
  spec/tapioca/compilers/dsl/active_record_associations_spec.rb
  spec/tapioca/compilers/dsl/active_record_columns_spec.rb
  spec/tapioca/compilers/dsl/active_record_enum_spec.rb
  spec/tapioca/compilers/dsl/active_record_fixtures_spec.rb
  spec/tapioca/compilers/dsl/active_record_scope_spec.rb
  spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
  spec/tapioca/compilers/dsl/active_resource_spec.rb
  spec/tapioca/compilers/dsl/active_storage_spec.rb
  spec/tapioca/compilers/dsl/active_support_concern_spec.rb
  spec/tapioca/compilers/dsl/active_support_current_attributes_spec.rb
  spec/tapioca/compilers/dsl/config_spec.rb
  spec/tapioca/compilers/dsl/frozen_record_spec.rb
  spec/tapioca/compilers/dsl/identity_cache_spec.rb
  spec/tapioca/compilers/dsl/mixed_in_class_attributes_spec.rb
  spec/tapioca/compilers/dsl/protobuf_spec.rb
  spec/tapioca/compilers/dsl/rails_generators_spec.rb
  spec/tapioca/compilers/dsl/sidekiq_worker_spec.rb
  spec/tapioca/compilers/dsl/smart_properties_spec.rb
  spec/tapioca/compilers/dsl/state_machines_spec.rb
  spec/tapioca/compilers/dsl/url_helpers_spec.rb
Labels: enhancement

#787 Replace usage of `T::Private::Methods.signature_for_method` with public equivalent
  lib/tapioca/compilers/dsl/base.rb
  lib/tapioca/compilers/dsl/helpers/active_record_column_type_helper.rb
  lib/tapioca/reflection.rb
Labels: chore

#790 Rename `DslCompiler` to `DslPipeline`
  lib/tapioca/compilers/dsl/base.rb
  lib/tapioca/compilers/dsl_pipeline.rb
  lib/tapioca/generators/dsl.rb
  lib/tapioca/helpers/test/dsl_compiler.rb
  lib/tapioca/internal.rb
Labels: chore

#785 Proposal: split SymbolTableCompiler in multiple listeners
  lib/tapioca/compilers/gem/events.rb
  lib/tapioca/compilers/gem/listeners.rb
  lib/tapioca/compilers/gem/listeners/base.rb
  lib/tapioca/compilers/gem/listeners/dynamic_mixins.rb
  lib/tapioca/compilers/gem/listeners/methods.rb
  lib/tapioca/compilers/gem/listeners/mixins.rb
  lib/tapioca/compilers/gem/listeners/remove_empty_payload_scopes.rb
  lib/tapioca/compilers/gem/listeners/sorbet_enums.rb
  lib/tapioca/compilers/gem/listeners/sorbet_helpers.rb
  lib/tapioca/compilers/gem/listeners/sorbet_props.rb
  lib/tapioca/compilers/gem/listeners/sorbet_required_ancestors.rb
  lib/tapioca/compilers/gem/listeners/sorbet_signatures.rb
  lib/tapioca/compilers/gem/listeners/sorbet_type_variables.rb
  lib/tapioca/compilers/gem/listeners/subconstants.rb
  lib/tapioca/compilers/gem/listeners/yard_doc.rb
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/internal.rb
Labels: chore

#802 Bump rbi to v0.0.12
  Gemfile.lock
  tapioca.gemspec
Labels: dependencies

#809 Extract RBI helper
  lib/tapioca/compilers/gem/listeners/sorbet_signatures.rb
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/helpers/rbi_helper.rb
  lib/tapioca/internal.rb
Labels: chore

#771 Implement support for final method signatures
  lib/tapioca/compilers/gem/listeners/sorbet_signatures.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: bugfix

#780 Use root/absolute namespace in compiled RBI
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/sorbet_ext/name_patch.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
  spec/tapioca/dsl/compilers/action_controller_helpers_spec.rb
  spec/tapioca/dsl/compilers/action_mailer_spec.rb
  spec/tapioca/dsl/compilers/active_job_spec.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
  spec/tapioca/dsl/compilers/active_support_current_attributes_spec.rb
  spec/tapioca/dsl/compilers/sidekiq_worker_spec.rb
Labels: enhancement

#795 Refactor DSL compilers
  lib/tapioca/cli.rb
  lib/tapioca/commands/dsl.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/compilers.rb
  lib/tapioca/dsl/compilers/aasm.rb
  lib/tapioca/dsl/compilers/action_controller_helpers.rb
  lib/tapioca/dsl/compilers/action_mailer.rb
  lib/tapioca/dsl/compilers/active_job.rb
  lib/tapioca/dsl/compilers/active_model_attributes.rb
  lib/tapioca/dsl/compilers/active_model_secure_password.rb
  lib/tapioca/dsl/compilers/active_record_associations.rb
  lib/tapioca/dsl/compilers/active_record_columns.rb
  lib/tapioca/dsl/compilers/active_record_enum.rb
  lib/tapioca/dsl/compilers/active_record_fixtures.rb
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/dsl/compilers/active_record_scope.rb
  lib/tapioca/dsl/compilers/active_record_typed_store.rb
  lib/tapioca/dsl/compilers/active_resource.rb
  lib/tapioca/dsl/compilers/active_storage.rb
  lib/tapioca/dsl/compilers/active_support_concern.rb
  lib/tapioca/dsl/compilers/active_support_current_attributes.rb
  lib/tapioca/dsl/compilers/config.rb
  lib/tapioca/dsl/compilers/frozen_record.rb
  lib/tapioca/dsl/compilers/identity_cache.rb
  lib/tapioca/dsl/compilers/mixed_in_class_attributes.rb
  lib/tapioca/dsl/compilers/protobuf.rb
  lib/tapioca/dsl/compilers/rails_generators.rb
  lib/tapioca/dsl/compilers/sidekiq_worker.rb
  lib/tapioca/dsl/compilers/smart_properties.rb
  lib/tapioca/dsl/compilers/state_machines.rb
  lib/tapioca/dsl/compilers/url_helpers.rb
  lib/tapioca/dsl/helpers/active_record_constants_helper.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/helpers/test/dsl_compiler.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: breaking-change

#815 Move gems RBI generation things under `Tapioca::Gem`
  lib/tapioca.rb
  lib/tapioca/commands/gem.rb
  lib/tapioca/compilers/gem/events.rb
  lib/tapioca/compilers/gem/listeners.rb
  lib/tapioca/compilers/gem/listeners/base.rb
  lib/tapioca/compilers/gem/listeners/dynamic_mixins.rb
  lib/tapioca/compilers/gem/listeners/methods.rb
  lib/tapioca/compilers/gem/listeners/mixins.rb
  lib/tapioca/compilers/gem/listeners/remove_empty_payload_scopes.rb
  lib/tapioca/compilers/gem/listeners/sorbet_enums.rb
  lib/tapioca/compilers/gem/listeners/sorbet_helpers.rb
  lib/tapioca/compilers/gem/listeners/sorbet_props.rb
  lib/tapioca/compilers/gem/listeners/sorbet_required_ancestors.rb
  lib/tapioca/compilers/gem/listeners/sorbet_signatures.rb
  lib/tapioca/compilers/gem/listeners/sorbet_type_variables.rb
  lib/tapioca/compilers/gem/listeners/subconstants.rb
  lib/tapioca/compilers/gem/listeners/yard_doc.rb
  lib/tapioca/gem/events.rb
  lib/tapioca/gem/listeners.rb
  lib/tapioca/gem/listeners/base.rb
  lib/tapioca/gem/listeners/dynamic_mixins.rb
  lib/tapioca/gem/listeners/methods.rb
  lib/tapioca/gem/listeners/mixins.rb
  lib/tapioca/gem/listeners/remove_empty_payload_scopes.rb
  lib/tapioca/gem/listeners/sorbet_enums.rb
  lib/tapioca/gem/listeners/sorbet_helpers.rb
  lib/tapioca/gem/listeners/sorbet_props.rb
  lib/tapioca/gem/listeners/sorbet_required_ancestors.rb
  lib/tapioca/gem/listeners/sorbet_signatures.rb
  lib/tapioca/gem/listeners/sorbet_type_variables.rb
  lib/tapioca/gem/listeners/subconstants.rb
  lib/tapioca/gem/listeners/yard_doc.rb
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/helpers/sorbet_helper.rb
  lib/tapioca/helpers/test/isolation.rb
  lib/tapioca/helpers/test/template.rb
  lib/tapioca/internal.rb
  spec/helpers/mock_project.rb
  spec/tapioca/cli/gem_spec.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: chore

#816 Create `Tapioca::Runtime` namespace
  lib/tapioca.rb
  lib/tapioca/commands/dsl.rb
  lib/tapioca/commands/gem.rb
  lib/tapioca/compilers/dynamic_mixin_compiler.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/compilers/mixed_in_class_attributes.rb
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/gem/listeners/dynamic_mixins.rb
  lib/tapioca/gem/listeners/methods.rb
  lib/tapioca/gem/listeners/mixins.rb
  lib/tapioca/gem/listeners/remove_empty_payload_scopes.rb
  lib/tapioca/gem/listeners/sorbet_helpers.rb
  lib/tapioca/gem/listeners/sorbet_required_ancestors.rb
  lib/tapioca/gem/listeners/sorbet_signatures.rb
  lib/tapioca/gem/listeners/sorbet_type_variables.rb
  lib/tapioca/gem/listeners/subconstants.rb
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/generic_type_registry.rb
  lib/tapioca/internal.rb
  lib/tapioca/loader.rb
  lib/tapioca/rbi_ext/model.rb
  lib/tapioca/reflection.rb
  lib/tapioca/runtime/dynamic_mixin_compiler.rb
  lib/tapioca/runtime/generic_type_registry.rb
  lib/tapioca/runtime/loader.rb
  lib/tapioca/runtime/reflection.rb
  lib/tapioca/runtime/trackers.rb
  lib/tapioca/runtime/trackers/autoload.rb
  lib/tapioca/runtime/trackers/constant_definition.rb
  lib/tapioca/runtime/trackers/mixin.rb
  lib/tapioca/runtime/trackers/required_ancestor.rb
  lib/tapioca/sorbet_ext/generic_name_patch.rb
  lib/tapioca/sorbet_ext/name_patch.rb
  lib/tapioca/symbol_loader.rb
  lib/tapioca/trackers/autoload.rb
  lib/tapioca/trackers/constant_definition.rb
  lib/tapioca/trackers/mixin.rb
  lib/tapioca/trackers/required_ancestor.rb
  spec/tapioca/reflection_spec.rb
  spec/tapioca/runtime/reflection_spec.rb
  tasks/generator_documentation.rake
Labels: chore, breaking-change

#817 Create `Tapioca::Static` namespace
  lib/tapioca/commands/require.rb
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/internal.rb
  lib/tapioca/static/requires_compiler.rb
  lib/tapioca/static/symbol_loader.rb
  lib/tapioca/static/symbol_table_parser.rb
  lib/tapioca/symbol_loader.rb
  lib/tapioca/symbol_table_parser.rb
  spec/tapioca/static/requires_compiler_spec.rb
Labels: chore

#819 Rename `Dsl::Compiler::Elem` into `ConstantType`
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/compilers/aasm.rb
  lib/tapioca/dsl/compilers/action_controller_helpers.rb
  lib/tapioca/dsl/compilers/action_mailer.rb
  lib/tapioca/dsl/compilers/active_job.rb
  lib/tapioca/dsl/compilers/active_model_attributes.rb
  lib/tapioca/dsl/compilers/active_model_secure_password.rb
  lib/tapioca/dsl/compilers/active_record_associations.rb
  lib/tapioca/dsl/compilers/active_record_columns.rb
  lib/tapioca/dsl/compilers/active_record_enum.rb
  lib/tapioca/dsl/compilers/active_record_fixtures.rb
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/dsl/compilers/active_record_scope.rb
  lib/tapioca/dsl/compilers/active_record_typed_store.rb
  lib/tapioca/dsl/compilers/active_resource.rb
  lib/tapioca/dsl/compilers/active_storage.rb
  lib/tapioca/dsl/compilers/active_support_concern.rb
  lib/tapioca/dsl/compilers/active_support_current_attributes.rb
  lib/tapioca/dsl/compilers/config.rb
  lib/tapioca/dsl/compilers/frozen_record.rb
  lib/tapioca/dsl/compilers/identity_cache.rb
  lib/tapioca/dsl/compilers/mixed_in_class_attributes.rb
  lib/tapioca/dsl/compilers/protobuf.rb
  lib/tapioca/dsl/compilers/rails_generators.rb
  lib/tapioca/dsl/compilers/sidekiq_worker.rb
  lib/tapioca/dsl/compilers/smart_properties.rb
  lib/tapioca/dsl/compilers/state_machines.rb
  lib/tapioca/dsl/compilers/url_helpers.rb
Labels: chore

#821 Load nothing from Tapioca by default
  lib/tapioca.rb
  lib/tapioca/internal.rb
  lib/tapioca/sorbet_ext/generic_name_patch.rb
Labels: breaking-change

#823 Fix path to dsl extensions
  lib/tapioca/commands/dsl.rb
Labels: bugfix

#830 Change default dev Ruby to 3.1
  dev.yml
  sorbet/rbi/gems/actioncable@6.1.4.6.rbi
  sorbet/rbi/gems/actionmailbox@6.1.4.6.rbi
  sorbet/rbi/gems/actionmailer@6.1.4.6.rbi
  sorbet/rbi/gems/actionpack@6.1.4.6.rbi
  sorbet/rbi/gems/actiontext@6.1.4.6.rbi
  sorbet/rbi/gems/actionview@6.1.4.6.rbi
  sorbet/rbi/gems/activejob@6.1.4.6.rbi
  sorbet/rbi/gems/activemodel-serializers-xml@1.0.2.rbi
  sorbet/rbi/gems/activemodel@6.1.4.6.rbi
  sorbet/rbi/gems/activerecord-typedstore@1.4.0.rbi
  sorbet/rbi/gems/activerecord@6.1.4.6.rbi
  sorbet/rbi/gems/activeresource@6.0.0.rbi
  sorbet/rbi/gems/activestorage@6.1.4.6.rbi
  sorbet/rbi/gems/activesupport@6.1.4.6.rbi
  sorbet/rbi/gems/byebug@11.1.3.rbi
  sorbet/rbi/gems/coderay@1.1.3.rbi
  sorbet/rbi/gems/concurrent-ruby@1.1.9.rbi
  sorbet/rbi/gems/config@4.0.0.rbi
  sorbet/rbi/gems/frozen_record@0.23.0.rbi
  sorbet/rbi/gems/globalid@1.0.0.rbi
  sorbet/rbi/gems/google-protobuf@3.19.4.rbi
  sorbet/rbi/gems/loofah@2.14.0.rbi
  sorbet/rbi/gems/mail@2.7.1.rbi
  sorbet/rbi/gems/minitest-reporters@1.5.0.rbi
  sorbet/rbi/gems/minitest@5.15.0.rbi
  sorbet/rbi/gems/parser@3.1.0.0.rbi
  sorbet/rbi/gems/pry-byebug@3.9.0.rbi
  sorbet/rbi/gems/pry@0.13.1.rbi
  sorbet/rbi/gems/rack-test@1.1.0.rbi
  sorbet/rbi/gems/rack@2.2.3.rbi
  sorbet/rbi/gems/rails-dom-testing@2.0.3.rbi
  sorbet/rbi/gems/rails-html-sanitizer@1.4.2.rbi
  sorbet/rbi/gems/rails@6.1.4.6.rbi
  sorbet/rbi/gems/railties@6.1.4.6.rbi
  sorbet/rbi/gems/rake@13.0.6.rbi
  sorbet/rbi/gems/rbi@0.0.12.rbi
  sorbet/rbi/gems/redis@4.6.0.rbi
  sorbet/rbi/gems/regexp_parser@2.2.0.rbi
  sorbet/rbi/gems/rubocop-ast@1.15.1.rbi
  sorbet/rbi/gems/rubocop@1.25.0.rbi
  sorbet/rbi/gems/ruby-progressbar@1.11.0.rbi
  sorbet/rbi/gems/shopify-money@0.16.0.rbi
  sorbet/rbi/gems/spoom@1.1.8.rbi
  sorbet/rbi/gems/sprockets-rails@3.4.2.rbi
  sorbet/rbi/gems/sprockets@4.0.2.rbi
  sorbet/rbi/gems/webrick@1.7.0.rbi
  sorbet/rbi/gems/websocket-driver@0.7.5.rbi
  sorbet/rbi/gems/yard-sorbet@0.6.1.rbi
Labels: chore

#831 Bump `nokogiri` to v1.13.3
  Gemfile.lock
Labels: dependencies
