Repository Shopify/tapioca, pull requests merged in 2022-10, with the labels that each got.

#1202 Filter backtrace locations in test errors
  spec/spec_helper.rb
Labels: chore

#1208 Show error and fail early for unknown options
  lib/tapioca/cli.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: enhancement

#1238 ci: regenerate Gemfile.lock when running on ruby head
  .github/workflows/ci.yml
Labels: chore

#1246 Update gems and their RBI files
  Gemfile.lock
  sorbet/rbi/gems/google-protobuf@3.21.8.rbi
  sorbet/rbi/gems/graphql@2.0.15.rbi
  sorbet/rbi/gems/rubocop-rspec@2.14.1.rbi
Labels: dependencies

#1249 Avoid installing prerelease bundler for mock project
  spec/helpers/mock_project.rb
Labels: chore
