Repository Shopify/tapioca, pull requests merged in 2022-06, with the labels that each got.

#956 Fix command documentation for check-shims
  README.md
Labels: documentation

#965 Fix CI
  tasks/generator_documentation.rake
Labels: chore

#974 Clean requires
  lib/tapioca/commands/annotations.rb
  lib/tapioca/dsl.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/compilers.rb
  lib/tapioca/dsl/helpers/param_helper.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/executor.rb
  lib/tapioca/gem.rb
  lib/tapioca/gem/events.rb
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/gemfile.rb
  lib/tapioca/helpers/cli_helper.rb
  lib/tapioca/helpers/config_helper.rb
  lib/tapioca/helpers/sorbet_helper.rb
  lib/tapioca/helpers/test/content.rb
  lib/tapioca/helpers/test/template.rb
  lib/tapioca/internal.rb
  lib/tapioca/runtime/trackers/constant_definition.rb
  lib/tapioca/sorbet_ext/generic_name_patch.rb
  lib/tapioca/static/requires_compiler.rb
  lib/tapioca/static/symbol_loader.rb
  lib/tapioca/static/symbol_table_parser.rb
Labels: chore

#963 Support authentification for private annotations repositories
  Gemfile
  Gemfile.lock
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/commands/annotations.rb
  sorbet/rbi/gems/addressable@2.8.0.rbi
  sorbet/rbi/gems/crack@0.4.5.rbi
  sorbet/rbi/gems/hashdiff@1.0.1.rbi
  sorbet/rbi/gems/public_suffix@4.0.7.rbi
  sorbet/rbi/gems/webmock@3.14.0.rbi
  spec/tapioca/cli/annotations_spec.rb
  spec/tapioca/commands/annotations_spec.rb
  tasks/readme.rake
Labels: enhancement

#987 Better name validation for methods and parameters
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/gem/listeners/methods.rb
  lib/tapioca/helpers/rbi_helper.rb
  lib/tapioca/rbi_ext/model.rb
  sorbet/rbi/gems/rbi@0.0.14.rbi
  spec/tapioca/helpers/rbi_helper_spec.rb
Labels: bugfix

#990 Read private repo credentials from a the netrc file
  Gemfile.lock
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/commands/annotations.rb
  lib/tapioca/helpers/cli_helper.rb
  lib/tapioca/internal.rb
  sorbet/rbi/gems/netrc@0.11.0.rbi
  spec/tapioca/cli/annotations_spec.rb
  spec/tapioca/commands/annotations_spec.rb
  tapioca.gemspec
Labels: enhancement

#994 Bump Ruby LSP version to 0.1.0
  Gemfile.lock
  sorbet/rbi/gems/ruby-lsp@0.1.0.rbi
Labels: dependencies

#995 Filter engines in application directory so they are not loaded
  lib/tapioca/gemfile.rb
  lib/tapioca/helpers/gem_helper.rb
  lib/tapioca/internal.rb
  lib/tapioca/runtime/loader.rb
  spec/tapioca/cli/gem_spec.rb
Labels: bugfix

#1011 Rename parameter `doc` into `include_doc`
  lib/tapioca/cli.rb
  lib/tapioca/commands/gem.rb
Labels: chore

#1007 Dsl::Compilers::ActiveRecordRelations: fix #find_sole_by, #sole
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1018 Use default gemfile path instead of Rails root when listing engines
  lib/tapioca/runtime/loader.rb
Labels: bugfix
