Repository Shopify/tapioca, pull requests merged in 2022-01, with the labels that each got.

#679 Start testing against Ruby 3.1
  .github/workflows/ci.yml
  Gemfile
  Gemfile.lock
  lib/tapioca/gemfile.rb
  spec/tapioca/compilers/dsl/action_mailer_spec.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
  spec/tapioca/gemfile_spec.rb
Labels: chore

#681 RequiresCompiler: handle ruby source files with alternate encodings
  lib/tapioca/compilers/requires_compiler.rb
  spec/tapioca/compilers/requires_compiler_spec.rb
Labels: enhancement

#683 Ignore interpolated strings in RequiresCompiler
  lib/tapioca/compilers/requires_compiler.rb
  spec/tapioca/compilers/requires_compiler_spec.rb
Labels: bugfix

#686 Upgrade Sorbet to 0.5.9468
  Gemfile.lock
Labels: dependencies, ruby, ignore-for-release

#709 Add configuration validation
  lib/tapioca/helpers/config_helper.rb
  spec/tapioca/cli/config_spec.rb
Labels: enhancement

#705 Allow extended/included T::Props* to be present in .rbi
  lib/tapioca/compilers/dynamic_mixin_compiler.rb
  lib/tapioca/compilers/symbol_table/symbol_generator.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: enhancement, help wanted

#712 Make generic AR column types `T.untyped`
  lib/tapioca/compilers/dsl/active_record_columns.rb
  lib/tapioca/generic_type_registry.rb
  lib/tapioca/helpers/active_record_column_type_helper.rb
  spec/tapioca/compilers/dsl/active_record_columns_spec.rb
Labels: bugfix

#706 Replace `clean-shims` by `check-shims`
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/helpers/shims_helper.rb
  lib/tapioca/internal.rb
  spec/tapioca/cli/check_shims_spec.rb
  spec/tapioca/cli/clean_shims_spec.rb
Labels: feature, breaking-change

#718 Bump `sorbet` and `sorbet-runtime` to 0.5.9542
  Gemfile.lock
Labels: dependencies

#721 Bump Thor requirement
  Gemfile.lock
  tapioca.gemspec
Labels: bug, breaking-change

#720 Add `gems` as an alias to the `gem` command
  lib/tapioca/cli.rb
  spec/tapioca/cli/gem_spec.rb
Labels: enhancement

#735 Merge SymbolTable::SymbolGenerator into SymbolTableCompiler
  lib/tapioca/compilers/symbol_table/symbol_generator.rb
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/generators/gem.rb
  lib/tapioca/internal.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: chore

#733 Extract `sorbet_helper` module
  lib/tapioca/compilers/dsl/active_record_relations.rb
  lib/tapioca/compilers/dsl/active_support_concern.rb
  lib/tapioca/compilers/sorbet.rb
  lib/tapioca/compilers/symbol_table/symbol_loader.rb
  lib/tapioca/generators/todo.rb
  lib/tapioca/helpers/sorbet_helper.rb
  lib/tapioca/internal.rb
  spec/tapioca/compilers/dsl/active_record_relations_spec.rb
  spec/tapioca/compilers/sorbet_spec.rb
  spec/tapioca/helpers/sorbet_spec.rb
Labels: chore

#730 Fix Dependabot labels
  .github/dependabot.yml
Labels: chore

#736 Clean useless things
  lib/tapioca/rbi_ext/model.rb
Labels: chore

#738 Update RBIs for gems
  sorbet/rbi/gems/actionmailbox@6.1.3.2.rbi
  sorbet/rbi/gems/actionpack@6.1.3.2.rbi
  sorbet/rbi/gems/actiontext@6.1.3.2.rbi
  sorbet/rbi/gems/activejob@6.1.3.2.rbi
  sorbet/rbi/gems/activemodel-serializers-xml@1.0.2.rbi
  sorbet/rbi/gems/activemodel@6.1.3.2.rbi
  sorbet/rbi/gems/activerecord-typedstore@1.3.2.rbi
  sorbet/rbi/gems/activerecord@6.1.3.2.rbi
  sorbet/rbi/gems/activeresource@5.1.1.rbi
  sorbet/rbi/gems/activesupport@6.1.3.2.rbi
  sorbet/rbi/gems/builder@3.2.4.rbi
  sorbet/rbi/gems/byebug@11.1.3.rbi
  sorbet/rbi/gems/digest@3.1.0.rbi
  sorbet/rbi/gems/globalid@1.0.0.rbi
  sorbet/rbi/gems/google-protobuf@3.19.2.rbi
  sorbet/rbi/gems/i18n@1.8.10.rbi
  sorbet/rbi/gems/identity_cache@1.1.0.rbi
  sorbet/rbi/gems/io-wait@0.2.1.rbi
  sorbet/rbi/gems/mail@2.7.1.rbi
  sorbet/rbi/gems/minitest-reporters@1.5.0.rbi
  sorbet/rbi/gems/minitest@5.14.4.rbi
  sorbet/rbi/gems/net-protocol@0.1.2.rbi
  sorbet/rbi/gems/net-smtp@0.3.1.rbi
  sorbet/rbi/gems/parser@3.0.2.0.rbi
  sorbet/rbi/gems/pry@0.13.1.rbi
  sorbet/rbi/gems/rails-dom-testing@2.0.3.rbi
  sorbet/rbi/gems/rails-html-sanitizer@1.3.0.rbi
  sorbet/rbi/gems/rake@13.0.6.rbi
  sorbet/rbi/gems/rbi@0.0.9.rbi
  sorbet/rbi/gems/redis@4.2.5.rbi
  sorbet/rbi/gems/regexp_parser@2.1.1.rbi
  sorbet/rbi/gems/rubocop-ast@1.7.0.rbi
  sorbet/rbi/gems/rubocop@1.17.0.rbi
  sorbet/rbi/gems/shopify-money@0.16.0.rbi
  sorbet/rbi/gems/sprockets-rails@3.2.2.rbi
  sorbet/rbi/gems/sqlite3@1.4.2.rbi
  sorbet/rbi/gems/state_machines@0.5.0.rbi
  sorbet/rbi/gems/timeout@0.2.0.rbi
  sorbet/rbi/gems/xpath@3.2.0.rbi
  sorbet/rbi/gems/yard@0.9.26.rbi
  sorbet/rbi/shims/rdoc.rbi
  sorbet/tapioca/config.yml
Labels: chore

#744 Add rubocop rules for RSpec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  spec/tapioca/cli/gem_spec.rb
  spec/tapioca/compilers/dsl/aasm_spec.rb
  spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
  spec/tapioca/compilers/dsl/action_mailer_spec.rb
  spec/tapioca/compilers/dsl/active_job_spec.rb
  spec/tapioca/compilers/dsl/active_model_attributes_spec.rb
  spec/tapioca/compilers/dsl/active_record_associations_spec.rb
  spec/tapioca/compilers/dsl/active_record_columns_spec.rb
  spec/tapioca/compilers/dsl/active_record_enum_spec.rb
  spec/tapioca/compilers/dsl/active_record_fixtures_spec.rb
  spec/tapioca/compilers/dsl/active_record_scope_spec.rb
  spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
  spec/tapioca/compilers/dsl/active_resource_spec.rb
  spec/tapioca/compilers/dsl/active_storage_spec.rb
  spec/tapioca/compilers/dsl/active_support_concern_spec.rb
  spec/tapioca/compilers/dsl/active_support_current_attributes_spec.rb
  spec/tapioca/compilers/dsl/config_spec.rb
  spec/tapioca/compilers/dsl/frozen_record_spec.rb
  spec/tapioca/compilers/dsl/identity_cache_spec.rb
  spec/tapioca/compilers/dsl/mixed_in_class_attributes_spec.rb
  spec/tapioca/compilers/dsl/protobuf_spec.rb
  spec/tapioca/compilers/dsl/rails_generators_spec.rb
  spec/tapioca/compilers/dsl/sidekiq_worker_spec.rb
  spec/tapioca/compilers/dsl/smart_properties_spec.rb
  spec/tapioca/compilers/dsl/state_machines_spec.rb
  spec/tapioca/compilers/dsl/url_helpers_spec.rb
  spec/tapioca/compilers/requires_compiler_spec.rb
Labels: chore

#728 Generate `requires_ancestor` helpers in gems RBIs
  Gemfile.lock
  lib/tapioca/compilers/symbol_table_compiler.rb
  lib/tapioca/trackers.rb
  lib/tapioca/trackers/required_ancestor.rb
  sorbet/rbi/gems/rbi@0.0.10.rbi
  sorbet/rbi/gems/spoom@1.1.5.rbi
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
Labels: feature

#749 Remove old RBI
  sorbet/rbi/gems/rbi@0.0.9.rbi
Labels: chore

#761 Rename sorbet_helper_spec file
  spec/tapioca/helpers/sorbet_helper_spec.rb
Labels: chore

#762 Remove parenthesis around `describe` titles
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/cli/gem_spec.rb
  spec/tapioca/cli/init_spec.rb
  spec/tapioca/cli/require_spec.rb
  spec/tapioca/cli/todo_spec.rb
  spec/tapioca/cli/version_spec.rb
  spec/tapioca/compilers/dsl/aasm_spec.rb
  spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
  spec/tapioca/compilers/dsl/action_mailer_spec.rb
  spec/tapioca/compilers/dsl/active_job_spec.rb
  spec/tapioca/compilers/dsl/active_model_attributes_spec.rb
  spec/tapioca/compilers/dsl/active_model_secure_password_spec.rb
  spec/tapioca/compilers/dsl/active_record_associations_spec.rb
  spec/tapioca/compilers/dsl/active_record_columns_spec.rb
  spec/tapioca/compilers/dsl/active_record_enum_spec.rb
  spec/tapioca/compilers/dsl/active_record_fixtures_spec.rb
  spec/tapioca/compilers/dsl/active_record_relations_spec.rb
  spec/tapioca/compilers/dsl/active_record_scope_spec.rb
  spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
  spec/tapioca/compilers/dsl/active_resource_spec.rb
  spec/tapioca/compilers/dsl/active_storage_spec.rb
  spec/tapioca/compilers/dsl/active_support_concern_spec.rb
  spec/tapioca/compilers/dsl/active_support_current_attributes_spec.rb
  spec/tapioca/compilers/dsl/config_spec.rb
  spec/tapioca/compilers/dsl/frozen_record_spec.rb
  spec/tapioca/compilers/dsl/identity_cache_spec.rb
  spec/tapioca/compilers/dsl/mixed_in_class_attributes_spec.rb
  spec/tapioca/compilers/dsl/protobuf_spec.rb
  spec/tapioca/compilers/dsl/rails_generators_spec.rb
  spec/tapioca/compilers/dsl/sidekiq_worker_spec.rb
  spec/tapioca/compilers/dsl/smart_properties_spec.rb
  spec/tapioca/compilers/dsl/state_machines_spec.rb
  spec/tapioca/compilers/dsl/url_helpers_spec.rb
  spec/tapioca/compilers/requires_compiler_spec.rb
  spec/tapioca/compilers/symbol_table_compiler_spec.rb
  spec/tapioca/gemfile_spec.rb
  spec/tapioca/rbi_builder_spec.rb
  spec/tapioca/reflection_spec.rb
Labels: chore

#765 Remove MFA cop rule
  .rubocop.yml
Labels: chore
