Repository Shopify/tapioca, pull requests merged in 2023-09, with the labels that each got.

#1635 Add tests for `GenericTypeRegistry`
  spec/tapioca/runtime/generic_type_registry_spec.rb
Labels: enhancement

#1645 Bump `rbi` to v0.1.0
  Gemfile.lock
  sorbet/rbi/gems/diff-lcs@1.5.0.rbi
  sorbet/rbi/gems/rbi@0.1.0.rbi
  sorbet/rbi/gems/unparser@0.6.8.rbi
  sorbet/rbi/gems/yarp@0.10.0.rbi
  spec/tapioca/cli/annotations_spec.rb
  spec/tapioca/cli/check_shims_spec.rb
  spec/tapioca/cli/gem_spec.rb
  tapioca.gemspec
Labels: dependencies

#1648 Fix CI
  Gemfile.lock
  sorbet/rbi/gems/.gitattributes
  sorbet/rbi/gems/rbi@0.1.1.rbi
  sorbet/rbi/gems/yarp@0.11.0.rbi
  spec/tapioca/cli/annotations_spec.rb
  spec/tapioca/cli/check_shims_spec.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/cli/gem_spec.rb
Labels: chore
