Repository Shopify/tapioca, pull requests merged in 2024-09, with the labels that each got.

#2021 Fix CI on Ruby 3.3.5
  Gemfile.lock
  sorbet/rbi/gems/yard@0.9.37.rbi
  spec/helpers/mock_project.rb
  spec/tapioca/cli/check_shims_spec.rb
  spec/tapioca/cli/config_spec.rb
  spec/tapioca/cli/configure_spec.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/cli/gem_spec.rb
  spec/tapioca/cli/help_spec.rb
  spec/tapioca/cli/require_spec.rb
  spec/tapioca/cli/todo_spec.rb
  spec/tapioca/cli/version_spec.rb
Labels: chore

#2015 Correct type annotation in `ActiveRecordColumnTypeHelper's`
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
Labels: bugfix

#2010 Support Postgres Interval, Range, Bit, and BitVarying
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
  sorbet/rbi/shims/activerecord_postgresql.rbi
Labels: enhancement

#2026 Avoid a deprecation warning on Ruby 3.4 with the uri gem
  lib/tapioca/helpers/source_uri.rb
Labels: chore
