Repository Shopify/tapioca, pull requests merged in 2024-08, with the labels that each got.

#1978 Add a sig with no args for ActiveRecordRelations builder methods
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1980 Log Sorbet signature block errors that lead to misleading RBI signatures generated
  lib/tapioca/commands/abstract_gem.rb
  lib/tapioca/gem/listeners/methods.rb
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/loaders/loader.rb
  lib/tapioca/runtime/reflection.rb
  lib/tapioca/static/symbol_loader.rb
  spec/tapioca/gem/pipeline_spec.rb
  spec/tapioca/runtime/reflection_spec.rb
Labels: enhancement

#1983 Fix ActiveRecordRelations Model.new typing
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#2006 Bump RBI dependency to v0.2
  Gemfile.lock
  lib/tapioca/gem/listeners/sorbet_enums.rb
  lib/tapioca/rbi_formatter.rb
  sorbet/rbi/gems/prism@1.0.0.rbi
  sorbet/rbi/gems/rbi@0.2.0.rbi
  tapioca.gemspec
Labels: dependencies

#1989 Iterate over requested_constants in DSL helpers
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/pipeline.rb
Labels: enhancement, refactor

#2007 Fix types for composite primary keys
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
Labels: bugfix
