Repository Shopify/tapioca, pull requests merged in 2024-12, with the labels that each got.

#2109 Clarify DSL compiler contribution instructions
  README.md
Labels: documentation

#2122 Revert "Don't attempt to load built-in compilers multiple times"
  lib/tapioca/loaders/dsl.rb
Labels: bugfix

#2112 Provide a hook for custom `ActiveModel` types
  lib/tapioca/dsl/helpers/active_model_type_helper.rb
  spec/tapioca/dsl/compilers/active_model_attributes_spec.rb
  spec/tapioca/dsl/helpers/active_model_type_helper_spec.rb
Labels: enhancement

#2125 Rename `#sorbet_type` → `#__tapioca_type`
  lib/tapioca/dsl/compilers/json_api_client_resource.rb
  spec/tapioca/dsl/compilers/json_api_client_resource_spec.rb
Labels: enhancement, breaking-change

#2111 [Tapioca Addon] Handle missing gems gracefully in tapioca gem command
  lib/tapioca/cli.rb
  lib/tapioca/commands/abstract_gem.rb
  lib/tapioca/commands/gem_generate.rb
  spec/tapioca/cli/gem_spec.rb
Labels: enhancement
