Repository Shopify/tapioca, pull requests merged in 2024-02, with the labels that each got.

#1791 Simplify gemfiles
  .github/workflows/ci.yml
  Gemfile
  Gemfile.lock
  gemfiles/Gemfile-rails-7-0
  gemfiles/Gemfile-rails-main
Labels: chore

#1796 Add PR label action
  .github/workflows/require_label.yml
Labels: chore

#1801 Fix rack gem version in failing test
  spec/tapioca/cli/gem_spec.rb
Labels: ignore-for-release

#1802 Stronger checks for existence of `config` gem
  lib/tapioca/dsl/compilers/config.rb
Labels: bugfix

#1809 Bump `sorbet-static-and-runtime` requirement to v0.5.11087
  Gemfile.lock
  lib/tapioca/version.rb
  tapioca.gemspec
Labels: dependencies
