Repository Shopify/tapioca, pull requests merged in 2024-10, with the labels that each got.

#2029 Fix broken CI on Ruby 3.1
  .github/workflows/ci.yml
  spec/tapioca/cli/gem_spec.rb
Labels: chore

#2035 [Tapioca add-on] Add `ServerAddon` boilerplate
  .rubocop.yml
  lib/ruby_lsp/tapioca/addon.rb
  lib/ruby_lsp/tapioca/server_addon.rb
  sorbet/rbi/gems/ruby-lsp-rails@0.3.18.rbi
  sorbet/tapioca/require.rb
Labels: enhancement

#2037 [Tapioca add-on] Generate DSL RBIs in add-on mode
  lib/ruby_lsp/tapioca/addon.rb
  lib/ruby_lsp/tapioca/server_addon.rb
  lib/tapioca/cli.rb
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/loaders/dsl.rb
  tasks/readme.rake
Labels: enhancement

#2040 Log Tapioca Add-on Activation
  lib/ruby_lsp/tapioca/addon.rb
Labels: enhancement, chore

#2046 Bump expected rack version in tests
  spec/tapioca/cli/gem_spec.rb
Labels: chore

#2043 Fixes for AASM compiler
  lib/tapioca/dsl/compilers/aasm.rb
  spec/tapioca/dsl/compilers/aasm_spec.rb
Labels: enhancement

#2049 Assert project file existence using patterns
  spec/spec_with_project.rb
  spec/tapioca/cli/gem_spec.rb
Labels: chore
