Repository Shopify/tapioca, pull requests merged in 2024-11, with the labels that each got.

#2074 Various CI fixes
  Gemfile
  Gemfile.lock
  sorbet/rbi/gems/sqlite3@2.2.0.rbi
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/cli/gem_spec.rb
Labels: chore

#2070 Use method overloading to improve WhereChain definition
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#2073 Call `to_a` on cached `ObjectSpace` enumerator
  lib/tapioca/dsl/compiler.rb
Labels: bugfix

#2077 Avoid writing gitattributes file unless necessary
  lib/tapioca/helpers/git_attributes.rb
Labels: bugfix

#2084 Ensure only constants that extend Module are parsed from requested paths
  lib/tapioca/commands/abstract_dsl.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: bugfix

#2075 Warn when Tapioca is executed without Bundler
  exe/tapioca
Labels: chore

#2085 [Tapioca Add-on] Limit what we require from the Rails add-on
  lib/ruby_lsp/tapioca/addon.rb
Labels: bugfix

#2089 Infer the worker count for `tapioca dsl`
  README.md
  lib/tapioca/cli.rb
Labels: enhancement

#2094 Update Minitest for improved test running experience
  Gemfile.lock
  sorbet/rbi/gems/minitest@5.25.2.rbi
Labels: chore

#2093 [Tapioca Add-on] Generate DSL RBIs in add-on mode
  lib/ruby_lsp/tapioca/addon.rb
  lib/ruby_lsp/tapioca/server_addon.rb
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/dsl/compiler.rb
  sorbet/rbi/shims/uri.rbi
Labels: enhancement

#2097 Pass LSP add-on option to DSL
  lib/tapioca/cli.rb
Labels: bugfix

#2098 Pass lsp addon option to DSL loader
  lib/tapioca/commands/abstract_dsl.rb
Labels: bugfix

#2096 `--exclude` should also exclude transitive dependencies
  lib/tapioca/commands/abstract_gem.rb
  lib/tapioca/gemfile.rb
  spec/spec_with_project.rb
  spec/tapioca/cli/gem_spec.rb
Labels: enhancement
