Repository Shopify/tapioca, pull requests merged in 2024-06, with the labels that each got.

#1888 Start passing in an option to `ActiveRecordColumns` compiler for how to generate column types
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/dsl/compilers/active_record_columns.rb
  lib/tapioca/dsl/compilers/identity_cache.rb
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/helpers/config_helper.rb
  lib/tapioca/helpers/test/dsl_compiler.rb
  spec/spec_with_project.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
Labels: enhancement

#1915 Remove sorbet.highlightUntyped setting
  .vscode/settings.json
Labels: chore

#1923 Downgrade bundler in CI
  .github/workflows/ci.yml
Labels: chore

#1925 Make Rails engine path check more specific
  lib/tapioca/static/symbol_loader.rb
  spec/tapioca/cli/gem_spec.rb
Labels: bugfix

#1924 Support array types in `typed_store` compiler
  lib/tapioca/dsl/compilers/active_record_typed_store.rb
  spec/tapioca/dsl/compilers/active_record_typed_store_spec.rb
Labels: enhancement, feature

#1928 Check for constant definition before invoking
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
Labels: bugfix

#1931 Refactor DSL compiler options to be a flat namespaced hash and document them
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/dsl/compilers/active_record_columns.rb
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/helpers/config_helper.rb
  manual/compiler_activerecordcolumns.md
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
Labels: enhancement

#1933 fix: `ActiveSupportConcern` recursively checks for `ClassMethod`
  lib/tapioca/dsl/compilers/active_support_concern.rb
  spec/tapioca/dsl/compilers/active_support_concern_spec.rb
Labels: bugfix

#1585 Filter gem RBIs by version during `annotations` command
  lib/tapioca/commands/annotations.rb
  lib/tapioca/gem_info.rb
  lib/tapioca/internal.rb
  spec/tapioca/cli/annotations_spec.rb
  spec/tapioca/commands/annotations_spec.rb
Labels: enhancement

#1942 Fix ActiveRecordRelations compiler to dedup #all
  lib/tapioca/dsl/compilers/active_record_relations.rb
Labels: bugfix
