Repository Shopify/tapioca, pull requests merged in 2024-04, with the labels that each got.

#1853 Automatic stdout/stderr assertion updates
  spec/spec_with_project.rb
Labels: enhancement

#1844 Update Active Record find sig to allow a block
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/rbi_ext/model.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#1860 Update Active Record count sig to allow a block
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#1867 Remove extra ) in the ActiveRecord.find output
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1872 Do not notify Slack on synchronize
  .github/workflows/team_ruby_dx.yml
Labels: chore

#1830 generate overloaded sigs for active record sum
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/rbi_ext/model.rb
  sorbet/rbi/gems/rbi@0.1.10.rbi
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1871 Infer types for active record fixtures
  lib/tapioca/dsl/compilers/active_record_fixtures.rb
  manual/compiler_activerecordfixtures.md
  sorbet/rbi/shims/active_record_fixture_set.rbi
  spec/tapioca/dsl/compilers/active_record_fixtures_spec.rb
Labels: enhancement

#1878 Bump sorbet-static-and-runtime
  Gemfile.lock
Labels: dependencies

#1879 Use `T.any(Integer, Float, BigDecimal)` as the return type for ActiveRecord calculation methods
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1882 Improve ActiveRecord::QueryMethods#distinct
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1886 Fix various typos
  README.md
  lib/tapioca/dsl/compilers/action_controller_helpers.rb
  lib/tapioca/dsl/compilers/active_model_secure_password.rb
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/dsl/compilers/active_record_typed_store.rb
  lib/tapioca/dsl/compilers/config.rb
  lib/tapioca/dsl/compilers/protobuf.rb
  lib/tapioca/runtime/generic_type_registry.rb
  lib/tapioca/static/requires_compiler.rb
  manual/compiler_activerecordrelations.md
  manual/compiler_activerecordtypedstore.md
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
  spec/tapioca/dsl/compilers/smart_properties_spec.rb
  spec/tapioca/dsl/compilers/url_helpers_spec.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: chore
