Repository Shopify/tapioca, pull requests merged in 2024-07, with the labels that each got.

#1944 Fix AASM compiler's global callback method signatures
  lib/tapioca/dsl/compilers/aasm.rb
  spec/tapioca/dsl/compilers/aasm_spec.rb
Labels: bugfix

#1949 Fix gem RBI generation for Spoom's generic
  lib/tapioca/internal.rb
Labels: bugfix

#1956 Short circuit Rails app loading if Rails constant isn't defined
  lib/tapioca/loaders/loader.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: enhancement

#1935 Optimize `URLHelpers.gather_constants`
  lib/tapioca/dsl/compilers/url_helpers.rb
Labels: enhancement

#1963 Make DSL compiler test helper work without needing an extra require
  lib/tapioca/helpers/test/dsl_compiler.rb
Labels: bugfix

#1964 Bumping Ruby version to 3.3.4
  .ruby-version
Labels: chore

#1966 Fix ActiveRecordRelation compiler's handling of composite primary keys
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#1945 Fix the types for state-machine states
  lib/tapioca/dsl/compilers/state_machines.rb
  spec/tapioca/dsl/compilers/state_machines_spec.rb
Labels: bugfix

#1962 Add `ActiveSupportTimeExt` compiler
  lib/tapioca/dsl/compilers/active_support_time_ext.rb
  manual/compiler_activesupporttimeext.md
  manual/compilers.md
  spec/tapioca/dsl/compilers/active_support_time_ext_spec.rb
Labels: enhancement

#1969 Flip subtype checks (`<` → `>`)
  lib/tapioca/dsl/compilers/active_model_validations_confirmation.rb
  lib/tapioca/dsl/compilers/active_support_concern.rb
  lib/tapioca/dsl/compilers/graphql_input_object.rb
  lib/tapioca/dsl/compilers/graphql_mutation.rb
  lib/tapioca/dsl/compilers/identity_cache.rb
  lib/tapioca/dsl/compilers/json_api_client_resource.rb
  lib/tapioca/dsl/compilers/sidekiq_worker.rb
  lib/tapioca/dsl/compilers/smart_properties.rb
  lib/tapioca/dsl/compilers/state_machines.rb
Labels: chore
