Repository Shopify/tapioca, pull requests merged in 2024-01, with the labels that each got.

#1632 Add Action Text compiler
  lib/tapioca/dsl/compilers/action_text.rb
  manual/compiler_actiontext.md
  manual/compilers.md
  spec/tapioca/dsl/compilers/action_text_spec.rb
Labels: enhancement

#1714 Restore `type_for(type)` function
  lib/tapioca/dsl/compilers/graphql_input_object.rb
  lib/tapioca/dsl/compilers/graphql_mutation.rb
  lib/tapioca/dsl/helpers/graphql_type_helper.rb
  spec/tapioca/dsl/helpers/graphql_type_helper_spec.rb
Labels: refactor

#1760 This one weird trick will speed up our test runs...
  spec/tapioca/cli/gem_spec.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: chore

#1762 Check if prepare argument is a symbol or string
  lib/tapioca/dsl/helpers/graphql_type_helper.rb
  spec/tapioca/dsl/compilers/graphql_mutation_spec.rb
  spec/tapioca/dsl/helpers/graphql_type_helper_spec.rb
Labels: bugfix

#1774 Remove `net-smtp` dependency
  Gemfile
  Gemfile.lock
Labels: chore
