Repository Shopify/tapioca, pull requests merged in 2024-05, with the labels that each got.

#1885 Detach RBI header comment from top-level node (when generating YARD docs)
  lib/tapioca/rbi_formatter.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/cli/gem_spec.rb
Labels: bugfix

#1876 Trigger matrix status check for push and PR events
  .github/workflows/ci.yml
Labels: chore

#1877 Introduce `skip_constants` flag to `dsl`
  README.md
  lib/tapioca/cli.rb
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/dsl/pipeline.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: enhancement

#1889 Remove Ruby 3.0 from CI matrix
  .github/workflows/ci.yml
  tapioca.gemspec
Labels: chore

#1895 ActiveRecordFixtures compiler should support passing no args
  lib/tapioca/dsl/compilers/active_record_fixtures.rb
  manual/compiler_activerecordfixtures.md
  spec/tapioca/dsl/compilers/active_record_fixtures_spec.rb
Labels: bugfix

#1897 fix: add default keyword argument to kredis extension attributes
  lib/tapioca/dsl/extensions/kredis.rb
Labels: bugfix

#1896 Ignore missing constants for `--skip-constant` option
  lib/tapioca/commands/abstract_dsl.rb
Labels: enhancement

#1904 Handle ActiveRecord attributes inheriting from `EncryptedAttributeType` with custom `sigs`
  lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
  spec/tapioca/dsl/compilers/active_record_columns_spec.rb
Labels: enhancement

#1912 Do not report duplicate for shim or annotations classes redefining the superclass
  lib/tapioca/helpers/rbi_files_helper.rb
  spec/tapioca/cli/check_shims_spec.rb
Labels: bugfix
