Repository Shopify/tapioca, pull requests merged in 2024-03, with the labels that each got.

#1799 Add support for overloaded signatures and add overloaded ActiveRecordRelations sigs
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/rbi_ext/model.rb
  manual/compiler_activerecordrelations.md
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#1408 More accurately type ActiveRecordRelations calculation methods
  lib/tapioca/dsl/compilers/active_record_relations.rb
  lib/tapioca/dsl/helpers/active_record_constants_helper.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#1826 Prevent `abort` call within gem from breaking `tapioca gem` command
  lib/tapioca/commands/abstract_gem.rb
Labels: bugfix

#1835 Include the 'has_FIELD?' methods in RBIs generated from protobuf
  lib/tapioca/dsl/compilers/protobuf.rb
  spec/tapioca/dsl/compilers/protobuf_spec.rb
Labels: enhancement

#1823 Fix return type of ActiveRecord::QueryMethods#extract_associated
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#1846 Complete the `.ruby-version` standardization
  .github/workflows/ci.yml
  .rubocop.yml
Labels: chore

#1843 Fix ActiveRecordRelations compiler
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix
