Repository Shopify/tapioca, pull requests merged in 2025-07, with the labels that each got.

#2342 Fix handling of anonymous types in generic arguments
  lib/tapioca/sorbet_ext/name_patch.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: bugfix

#2271 use primary key type for ActiveRecord::Calculations#ids return type
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#2322 Replace Instances of Thor::Error with Tapioca::Error
  exe/tapioca
  lib/tapioca/cli.rb
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/commands/abstract_gem.rb
  lib/tapioca/commands/annotations.rb
  lib/tapioca/commands/check_shims.rb
  lib/tapioca/commands/gem_generate.rb
  lib/tapioca/dsl/pipeline.rb
  lib/tapioca/helpers/config_helper.rb
  lib/tapioca/helpers/rbi_files_helper.rb
  spec/tapioca/dsl/compilers/protobuf_spec.rb
Labels: chore

#2350 Ensure Dsl::Compiler extends T::Generic in server add-on
  lib/ruby_lsp/tapioca/server_addon.rb
Labels: bugfix

#2356 Generate Active Model attributes in an included `GeneratedAttributeMethods` module
  lib/tapioca/dsl/compilers/active_model_attributes.rb
  manual/compiler_activemodelattributes.md
  spec/tapioca/dsl/compilers/active_model_attributes_spec.rb
Labels: bugfix

#2364 Fix RBS comment prefix in YardDoc listener
  lib/tapioca/gem/listeners/yard_doc.rb
Labels: bugfix

#2363 Use `Bundler.load.specs` instead of reading `Gemfile.lock`
  lib/tapioca/commands/annotations.rb
  lib/tapioca/gem_info.rb
  spec/tapioca/cli/annotations_spec.rb
Labels: bugfix
