Repository Shopify/tapioca, pull requests merged in 2025-05, with the labels that each got.

#2262 Drop support for EOL Ruby 3.1
  .github/workflows/ci.yml
  spec/tapioca/dsl/compilers/action_mailer_spec.rb
  spec/tapioca/gem/pipeline_spec.rb
  tapioca.gemspec
Labels: dependencies

#2275 Make check-shims test more robust
  spec/tapioca/cli/check_shims_spec.rb
Labels: chore

#2236 Add support for RBS signature comments
  Gemfile.lock
  lib/tapioca/gem/events.rb
  lib/tapioca/gem/pipeline.rb
  lib/tapioca/internal.rb
  lib/tapioca/loaders/loader.rb
  lib/tapioca/rbs/rewriter.rb
  lib/tapioca/runtime/reflection.rb
  lib/tapioca/static/symbol_loader.rb
  sorbet/rbi/gems/actionpack@7.1.5.1.rbi
  sorbet/rbi/gems/activejob@7.1.5.1.rbi
  sorbet/rbi/gems/activemodel@7.1.5.1.rbi
  sorbet/rbi/gems/activeresource@6.1.4.rbi
  sorbet/rbi/gems/activesupport@7.1.5.1.rbi
  sorbet/rbi/gems/globalid@1.2.1.rbi
  sorbet/rbi/gems/identity_cache@1.6.3.rbi
  sorbet/rbi/gems/mail@2.8.1.rbi
  sorbet/rbi/gems/minitest-reporters@1.7.1.rbi
  sorbet/rbi/gems/minitest@5.25.5.rbi
  sorbet/rbi/gems/net-imap@0.5.7.rbi
  sorbet/rbi/gems/pp@0.6.2.rbi
  sorbet/rbi/gems/racc@1.8.1.rbi
  sorbet/rbi/gems/rack-session@2.0.0.rbi
  sorbet/rbi/gems/rack-test@2.1.0.rbi
  sorbet/rbi/gems/rake@13.2.1.rbi
  sorbet/rbi/gems/rbi@0.3.3.rbi
  sorbet/rbi/gems/rbs@4.0.0.dev.4.rbi
  sorbet/rbi/gems/require-hooks@0.2.2.rbi
  sorbet/rbi/gems/rubocop-ast@1.44.1.rbi
  sorbet/rbi/gems/ruby-lsp-rails@0.4.1.rbi
  sorbet/rbi/gems/ruby-lsp@0.23.15.rbi
  sorbet/rbi/gems/spoom@1.7.0.rbi
  sorbet/rbi/gems/state_machines@0.6.0.rbi
  sorbet/rbi/gems/uri@0.13.2.rbi
  sorbet/rbi/gems/yard-sorbet@0.9.0.rbi
  sorbet/rbi/gems/yard@0.9.37.rbi
  sorbet/tapioca/require.rb
  spec/tapioca/cli/dsl_spec.rb
  spec/tapioca/dsl/compilers/active_job_spec.rb
  spec/tapioca/gem/pipeline_spec.rb
  tapioca.gemspec
Labels: enhancement

#2285 Improve engine loading with Zeitwerk
  lib/tapioca/loaders/loader.rb
Labels: chore

#2273 Pin GitHub Actions to commit
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/require_label.yml
Labels: chore

#2286 Move `isolation` helper to `typed: strict`
  lib/tapioca/helpers/test/isolation.rb
Labels: chore

#2287 Load the runtime patches before Spoom
  lib/tapioca/internal.rb
Labels: bugfix

#2288 Ignore `@requires_ancestor` in `YardDoc` listener
  lib/tapioca/gem/listeners/yard_doc.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: bugfix

#2300 Eager load autoloads that are registered before the RBS rewriter is loaded
  lib/tapioca/internal.rb
  lib/tapioca/rbs/rewriter.rb
  lib/tapioca/runtime/trackers/autoload.rb
Labels: enhancement
