Repository Shopify/tapioca, pull requests merged in 2025-02, with the labels that each got.

#2193 Point Rails add-on to released version
  Gemfile
  Gemfile.lock
  sorbet/rbi/gems/ruby-lsp-rails@0.4.0.rbi
  sorbet/rbi/gems/ruby-lsp@0.23.9.rbi
Labels: chore

#2195 Introduce `addon_mode` ivar to Tapioca::Cli
  lib/ruby_lsp/tapioca/server_addon.rb
  lib/tapioca/cli.rb
Labels: enhancement

#2207 Raise `Thor::Error` instead of `exit`
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/dsl/pipeline.rb
  spec/tapioca/cli/dsl_spec.rb
Labels: bugfix

#2211 Bump add-on version to v0.1.3
  lib/ruby_lsp/tapioca/addon.rb
Labels: chore

#2213 Fix `fetch_annotation` signature
  lib/tapioca/commands/annotations.rb
Labels: bugfix
