Repository Shopify/tapioca, pull requests merged in 2025-01, with the labels that each got.

#2136 Update test expectations for parse errors
  spec/tapioca/cli/annotations_spec.rb
  spec/tapioca/cli/check_shims_spec.rb
  spec/tapioca/cli/gem_spec.rb
Labels: chore

#2139 Bump `sorbet-static-and-runtime`
  Gemfile.lock
  sorbet/rbi/gems/google-protobuf@4.29.2.rbi
  sorbet/rbi/gems/nokogiri@1.18.1.rbi
  sorbet/rbi/gems/sqlite3@2.5.0.rbi
Labels: chore

#2129 Support Bundler 2.6
  .github/workflows/ci.yml
  Gemfile.lock
  lib/tapioca/gemfile.rb
  spec/tapioca/gem/pipeline_spec.rb
Labels: bugfix

#2147 ActiveRecord `select` block returns `BasicObject`
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#2153 Fix signature of `GroupChain#size` method
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#2157 Return a Hash from `GroupChain#size`
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: bugfix

#2164 Upgrade Rails add-on to v0.3.31
  Gemfile.lock
  sorbet/rbi/gems/ruby-lsp-rails@0.3.31.rbi
Labels: chore

#2166 Avoid naming conflict for `URI::Source`
  lib/tapioca/gem/listeners/source_location.rb
  lib/tapioca/helpers/source_uri.rb
Labels: chore

#2165 Run URL helpers compiler when routes are modified
  lib/ruby_lsp/tapioca/addon.rb
  lib/ruby_lsp/tapioca/server_addon.rb
  spec/tapioca/addon_spec.rb
Labels: enhancement

#2163 [Tapioca Add-on] Trigger `ActiveSupport::TestCase` DSL compiler on fixture changes
  Gemfile
  Gemfile.lock
  lib/ruby_lsp/tapioca/addon.rb
  lib/ruby_lsp/tapioca/server_addon.rb
  spec/dummy/app/models/user.rb
  spec/dummy/config/application.rb
  spec/dummy/config/database.yml
  spec/tapioca/addon_spec.rb
Labels: enhancement

#2170 Prevent CI from running on both `push` and `pull_request` events
  .github/workflows/ci.yml
Labels: chore

#2171 Fix `chdir` issue for LSP
  lib/ruby_lsp/tapioca/addon.rb
  lib/ruby_lsp/tapioca/run_gem_rbi_check.rb
  spec/tapioca/ruby_lsp/run_gem_rbi_check_spec.rb
Labels: bugfix

#2176 Add progress indication for DSL operations
  lib/ruby_lsp/tapioca/server_addon.rb
Labels: enhancement

#2172 No-op if runner client is null
  lib/ruby_lsp/tapioca/addon.rb
Labels: bugfix
