Repository Shopify/tapioca, pull requests merged in 2025-06, with the labels that each got.

#2305 Bump development Ruby versiont o 3.4.4
  .ruby-version
Labels: chore

#2297 Mention ability to supply local annotations in README
  README.md
Labels: documentation

#2317 Do not load DSL compilers before extensions in add-on mode
  lib/ruby_lsp/tapioca/server_addon.rb
Labels: bugfix

#2315 Add support for cursor parameter on ActiveRecord's batch methods in Rails 8.0
  lib/tapioca/dsl/compilers/active_record_relations.rb
  spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Labels: enhancement

#2318 Translate class helpers to RBS comments
  lib/tapioca/bundler_ext/auto_require_hook.rb
  lib/tapioca/commands/abstract_dsl.rb
  lib/tapioca/commands/abstract_gem.rb
  lib/tapioca/commands/command.rb
  lib/tapioca/commands/command_without_tracker.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/gem/events.rb
  lib/tapioca/gem/listeners/base.rb
  lib/tapioca/helpers/cli_helper.rb
  lib/tapioca/helpers/config_helper.rb
  lib/tapioca/helpers/env_helper.rb
  lib/tapioca/helpers/rbi_files_helper.rb
  lib/tapioca/helpers/test/content.rb
  lib/tapioca/helpers/test/dsl_compiler.rb
  lib/tapioca/helpers/test/isolation.rb
  lib/tapioca/helpers/test/template.rb
  lib/tapioca/loaders/loader.rb
  lib/tapioca/runtime/attached_class_of_legacy.rb
  lib/tapioca/runtime/trackers/tracker.rb
Labels: chore

#2320 Translate abstract methods to RBS comments
  Gemfile.lock
  lib/tapioca/commands/command.rb
  lib/tapioca/dsl/compiler.rb
  lib/tapioca/loaders/loader.rb
Labels: chore

#2328 Relax Ruby LSP constraints to allow for v0.25
  lib/ruby_lsp/tapioca/addon.rb
Labels: chore

#2329 Wrap loading DSL compilers in notification handler
  lib/ruby_lsp/tapioca/server_addon.rb
Labels: bugfix

#2335 Fix single delegated_type
  lib/tapioca/dsl/compilers/active_record_delegated_types.rb
  spec/tapioca/dsl/compilers/active_record_delegated_types_spec.rb
Labels: bugfix
